version: "2"
services:
  framework:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: framework-server
    expose:
     - 80
     - 443
    ports:
      - "8080:80"
    volumes:
     - ./:/var/www/html
    links:
     - frameworkdb
    depends_on:
     - frameworkdb
  frameworkdb:
    image: mysql:5.7
    volumes:
     - ./config/mysql/:/var/lib/mysql
    environment:
     - MYSQL_DATABASE=frameworkdb
     - MYSQL_USER=frameworkdb
     - MYSQL_PASSWORD=p@ssw0rd
     - MYSQL_ROOT_PASSWORD=p@ssw0rd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8001:80"
    links:
      - frameworkdb
    depends_on:
      - frameworkdb
    environment:
      - MYSQL_USER=frameworkdb
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - PMA_HOST=frameworkdb