version: "2"
services:
  framework:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: framework-server
    expose:
     - 80
     - 443
    ports:
      - "8000:80"
    volumes:
     - ./:/var/www/html
    links:
     - mysql
    depends_on:
     - mysql
  mysql:
    image: mysql:5.7
    volumes:
     - ./config/mysql/:/var/lib/mysql
    environment:
     - MYSQL_DATABASE=framework
     - MYSQL_USER=ronflex
     - MYSQL_PASSWORD=kfixwoax
     - MYSQL_ROOT_PASSWORD=kfixwoax
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8001:80"
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=ronflex
      - MYSQL_PASSWORD=kfixwoax
      - MYSQL_ROOT_PASSWORD=kfixwoax
      - PMA_HOST=mysql